### ISSUE TITLE
Roadmap for new website release

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml.org#133]
- [x] Search: result list should allow endless scroll. Right now it stops after 100 items
- [ ] Search: add versioning info to datasets, show one version in results, allow switching versions
- [x] Search: filter menu is missing a submit button. Some filters (e.g. uploader) don't work
- [x] Routing: allow short URLs (e.g. /d/1 instead of /search?type=data&sort=runs&id=31)
- [x] Styling: Restyle cover page. Current version loads too slowly.
- [x] Styling: do minimal but clean styling of dataset, task, flow, run,... detail pages)
- [x] Styling: do minimal but clean styling of profile page, dataset upload, task/study creation forms
- [x] Interaction: make tags and users clickable
- [x] Interaction: list tasks for each dataset, runs for each task,...
- [x] Interaction: Add download/edit/fork buttons for datasets 
- [ ] Content: add quick examples for client APIs on API page, link to documentation pages
- [x] Content: Make new page for hackathons/workshops
- [x] Login: User avatar is not shown consistently after login (in navbar and edit profile page)

If you think of anything else, please add further todo items.

**Comment by prabhant** [comment]
- [x] Warning for image upload not working

- [x] Warning for Edit dataset not working

- [x] More detailed errors on frontend and backend

**Comment by joaquinvanschoren** [comment]
Some small styling issues:

- [x] Front page is too dense on small screens, needs more whitespace so that it's clear what belongs together.
- [x] OpenML in the header sometimes renders on two lines -> remove the space
- [x] One of the cards on the get_involved page isn't full width on large screens

**Comment by prabhant** [comment]
Configuration issues:

- [x] Solve DB connection issue [sqlalche.me/e/e3q8](url)

**Comment by joaquinvanschoren** [comment]
- [x] Update about page: have TC members, core developers, contributors,...

**Comment by joaquinvanschoren** [comment]
- [ ]  Add export [data, task, flow, run] ids function
- [ ] Add 'add to collection' on task page
- [ ] Add 'add to collection' on task search page 
- [ ] Add 'add to collection' on run page
- [ ] Add 'add to collection' on run search page

**Comment by prabhant** [comment]
- [ ] Fork backend and frontend
- [x] Dataset edit button

**Comment by joaquinvanschoren** [comment]
Closing this as the remaining tasks are better broken down into subtasks, for which I opened new issues.
